### ISSUE TITLE
Migrate to Webpack

### ISSUE THREAD

**Issue by Dwaynekj** [fin-hypergrid/core#525] opened 2017-02-08 18:00 UTC

**Comment by jjrv** [comment] 2017-02-10 08:07
I'm using SystemJS to bundle Hypergrid with my app. It's great! It works as-is, I just have to generate a config using: `cbuild -o dist/bundle.js -C config-npm.js` (command from the [`cbuild`](https://github.com/charto/cbuild) package).

Since it's using the Node.js entry point, I have to add this in my own code:

```TypeScript
window.fin = {
    Hypergrid: {analytics: analytics}
};
```

**Comment by Dwaynekj** [comment] 2017-02-10 16:50
@jjrv Thanks for the suggestion we will keep it under consideration when we get to this project later this spring

**Comment by aqumus** [comment] 2017-03-27 07:15
I have used fin-hypergrid npm package with basic webpack configuration and it was loading and working fine for me.

**Comment by dcchuck** [comment] 2017-09-12 21:00
@aqumus TY, confirmed. Closing.

**Closed by dcchuck** 2017-09-12 21:00 UTC
Labels: enhancement, help wanted, Open Discussions
