### ISSUE TITLE
ColumnSorting feature sends the wrong column index if there are hidden columns

### ISSUE THREAD

**Issue by nmichaud** [fin-hypergrid/core#670] opened 2018-01-04 15:12 UTC
This should use the index from the currently visible columns:

https://github.com/fin-hypergrid/core/blob/master/src/features/ColumnSorting.js#L24

**Comment by nmichaud** [comment] 2018-01-04 15:15
Something like this:

var column = grid.behavior.getActiveColumn(event.gridCell.x);
grid.fireSyntheticColumnSortEvent(column.index, event.primitiveEvent.detail.keys);

**Comment by joneit** [comment] 2018-01-08 12:28
As discussed, not a bug: The event data always refers to the “grid” (_i.e.,_ visible or active) column index. The `getActiveColumn` Call should be in the handler. Closing…

**Closed by joneit** 2018-01-08 12:28 UTC
